workspace:
  base: /srv/app
  path: src/github.com/appleboy/easyssh-proxy

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    secrets: [ codecov_token ]
    commands:
      - export PATH=$PATH:/srv/app/bin
      - make install
      - make vet
      - make lint
      - make embedmd
      - make ssh-server
      - coverage all
      - make coverage

    when:
      event: [ push, tag, pull_request ]
