workspace:
  base: /go/src
  path: github.com/appleboy/easyssh-proxy

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    secrets: [ codecov_token ]
    commands:
      - make install
      - make vet
      - make lint
      - make embedmd
      - make ssh-server
      - coverage all
      - make coverage

    when:
      event: [ push, tag, pull_request ]
