workspace:
  base: /go/src
  path: github.com/appleboy/easyssh-proxy

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test_vendor:
    image: appleboy/golang-testing
    pull: true
    group: testing
    secrets: [ codecov_token ]
    commands:
      - make install
      - make vet
      - make lint
      - make embedmd
      - make ssh-server
      - coverage all
      - make coverage
    when:
      event: [ push, tag, pull_request ]

  test_mod:
    image: golang:1.11-alpine3.8
    pull: true
    group: testing
    environment:
      - GO111MODULE=on
    commands:
      - apk add --no-cache git ca-certificates make gcc build-base zlib-dev ucl-dev
      - make ssh-server
      - make test
    when:
      event: [ push, tag, pull_request ]
