name: Lint and Testing

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

  testing:
    runs-on: ubuntu-latest
    container: golang:1.21-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup sshd server
        run: |
          apk add git make curl perl bash build-base zlib-dev ucl-dev sudo
          make ssh-server

      - name: testing
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
