name: Lint and Testing

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            go.tools.sum
          check-latest: true
      - name: Run golangci-lint
        run: make lint

  testing:
    runs-on: ubuntu-latest
    container: golang:1.26.8-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # all history for all branches and tags

      - name: setup sshd server
        run: |
          apk add git make curl perl bash build-base zlib-dev ucl-dev sudo gnupg
          make ssh-server

      - name: testing
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
